apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
  - host: ticketing.dev
    http: 
      paths: 
      - backend:
          service:
            name: auth-srv
            port:
              number: 8080
        path: /api/users/?(.*)
        pathType: Prefix
      - backend:
          service:
            name: client-srv
            port:
              number: 3000
        path: /?(.*)
        pathType: Prefix